#%RAML 0.8
description: |
    Resource not found, specifically occurs when a route is poorly specified,
    make sure that the resource ID are needing is correct.
body:
    example: !include ../examples/not-found-example.json