#%RAML 0.8
- User: !include schemas/user.json
- Particular: !include schemas/particular.json
- Address: !include schemas/address.json
- Email: !include schemas/email.json
- Phone: !include schemas/phone.json
- Establishment: !include schemas/establishment.json
- Administrator: !include schemas/administrator.json
- Role: !include schemas/role.json
- Permission: !include schemas/permission.json
- Operation: !include schemas/operation.json
- Messenger: !include schemas/messenger.json
- WorkshiftParam: !include schemas/workshiftParam.json
- Vehicle: !include schemas/vehicle.json
- Fault: !include schemas/fault.json
- Workshift: !include schemas/workshift.json
- Reliability: !include schemas/reliability.json